// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
import type {
  AppConfig,
  ExecutePlatformsRequest,
  ExecutePlatformsResponse,
  LicenseSnapshot,
  RuntimeConfig,
} from "@/types/config";
import type {
  LicenseActivationSummary,
  LicenseOperationResult,
} from "@/helpers/ipc/license/license-service";

export {};

declare global {
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
  }

  interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
  }

  interface ElectronShellContext {
    openExternal: (url: string) => Promise<void>;
  }

  interface RushLanguageContext {
    get: () => Promise<string>;
    set: (locale: string) => Promise<string>;
  }

  interface RushConfigContext {
    getConfig: () => Promise<RuntimeConfig>;
    saveConfig: (config: AppConfig) => Promise<void>;
    executePlatforms: (
      payload?: ExecutePlatformsRequest,
    ) => Promise<ExecutePlatformsResponse>;
    suspendShortcuts: () => void;
    resumeShortcuts: () => void;
  }

  interface RushLicenseContext {
    getStatus: () => Promise<LicenseSnapshot>;
    activate: (key: string) => Promise<LicenseOperationResult>;
    validate: () => Promise<LicenseOperationResult>;
    deactivate: () => Promise<LicenseOperationResult>;
    fetchActivationSummary: () => Promise<{
      success: boolean;
      snapshot: LicenseSnapshot;
      summary: LicenseActivationSummary | null;
      code?: string;
      message?: string;
    }>;
    watch: (
      listener: (snapshot: LicenseSnapshot) => void,
    ) => Promise<() => void>;
  }

  interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    electronShell: ElectronShellContext;
    rushConfig: RushConfigContext;
    rushLanguage: RushLanguageContext;
    rushLicense: RushLicenseContext;
  }
}
