// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
import type {
  AppConfigSavePayload,
  ExecutePlatformsRequest,
  ExecutePlatformsResponse,
  RuntimeConfig,
} from "@/types/config";
import type { AppLatestRelease, AppRuntimeInfo } from "@/types/app";

export {};

declare global {
  const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
  const MAIN_WINDOW_VITE_NAME: string;

  interface ThemeModeContext {
    toggle: () => Promise<boolean>;
    dark: () => Promise<void>;
    light: () => Promise<void>;
    system: () => Promise<boolean>;
    current: () => Promise<"dark" | "light" | "system">;
  }

  interface ElectronWindow {
    minimize: () => Promise<void>;
    maximize: () => Promise<void>;
    close: () => Promise<void>;
  }

  interface ElectronShellContext {
    openExternal: (url: string) => Promise<void>;
  }

  interface RushLanguageContext {
    get: () => Promise<string>;
    set: (locale: string) => Promise<string>;
  }

  interface RushConfigContext {
    getConfig: () => Promise<RuntimeConfig>;
    saveConfig: (config: AppConfigSavePayload) => Promise<void>;
    executePlatforms: (
      payload?: ExecutePlatformsRequest,
    ) => Promise<ExecutePlatformsResponse>;
    suspendShortcuts: () => void;
    resumeShortcuts: () => void;
  }

  interface RushAppContext {
    getVersion: () => Promise<string>;
    fetchLatestRelease: (options?: { channel?: string }) => Promise<
      | {
          ok: true;
          data: AppLatestRelease;
        }
      | {
          ok: false;
          status?: number;
          message: string;
        }
    >;
    getRuntimeInfo: () => Promise<AppRuntimeInfo>;
  }

  interface Window {
    themeMode: ThemeModeContext;
    electronWindow: ElectronWindow;
    electronShell: ElectronShellContext;
    rushConfig: RushConfigContext;
    rushLanguage: RushLanguageContext;
    rushApp: RushAppContext;
  }
}
